[build]
  command = "npm install --production=false"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "nft"
  included_files = ["node_modules/**"]

[[redirects]]
  from = "/.well-known/did.json"
  to = "/.netlify/functions/did"
  status = 200

[[redirects]]
  from = "/verify"
  to = "/.netlify/functions/verify"
  status = 200

[[redirects]]
  from = "/create/:documentId"
  to = "/.netlify/functions/create"
  status = 200

[dev]
  command = "npm run dev"
  port = 3001
